### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by eehres** [eehres/github_test#1]
### 만들고자 하는 기능이 무엇인가요?
1. [ ] Todo 생성 기능
2. [ ] Todo 삭제 기능
3. [ ] Todo 조회 기능
4. [ ] Todo 업데이트 기능
